apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duhigure-ingress
  namespace: duhigure
spec:
  ingressClassName: nginx
  rules:
  - host: www.duhigure.rw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: exam-duhigure-service
            port:
              number: 80
